//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnalisaMercadosCliente.MarketAnalyzesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:AnalisaMercadosWS", ConfigurationName="MarketAnalyzesWS.AnalisaMercadosWSPortType")]
    public interface AnalisaMercadosWSPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AnalisaMercadosWS/AnalisaMercados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        float AnalisaMercados(int ISBN, float price);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AnalisaMercadosWS/AnalisaMercados", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<float> AnalisaMercadosAsync(int ISBN, float price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AnalisaMercadosWSPortTypeChannel : AnalisaMercadosCliente.MarketAnalyzesWS.AnalisaMercadosWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnalisaMercadosWSPortTypeClient : System.ServiceModel.ClientBase<AnalisaMercadosCliente.MarketAnalyzesWS.AnalisaMercadosWSPortType>, AnalisaMercadosCliente.MarketAnalyzesWS.AnalisaMercadosWSPortType {
        
        public AnalisaMercadosWSPortTypeClient() {
        }
        
        public AnalisaMercadosWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnalisaMercadosWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalisaMercadosWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnalisaMercadosWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float AnalisaMercados(int ISBN, float price) {
            return base.Channel.AnalisaMercados(ISBN, price);
        }
        
        public System.Threading.Tasks.Task<float> AnalisaMercadosAsync(int ISBN, float price) {
            return base.Channel.AnalisaMercadosAsync(ISBN, price);
        }
    }
}
